import React, { useState, useEffect } from 'react';
import PageTransition from '../components/PageTransition';
import {
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  TextField,
  InputAdornment,
  Chip,
  LinearProgress,
  Alert,
  Grid,
  MenuItem,
  FormControl,
  InputLabel,
  Select,
  Tooltip,
  Card,
  CardContent,
  alpha,
  IconButton
} from '@mui/material';
import {
  Search as SearchIcon,
  History as HistoryIcon,
  Warning as WarningIcon,
  CheckCircle as CheckCircleIcon,
  PhoneAndroid as DeviceIcon,
  Update as UpdateIcon,
  Schedule as ScheduleIcon,
  Person as PersonIcon,
  Error as ErrorIcon,
  FilterList as FilterIcon,
  MoreVert as MoreIcon
} from '@mui/icons-material';
import { audit } from '../services/api';
import { format, formatDistance } from 'date-fns';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import Papa from 'papaparse';
import { Download as DownloadIcon } from '@mui/icons-material';
import { Button } from '@mui/material';
import { motion } from 'framer-motion';

const ORANGE = '#FF6B35';

const AuditStatCard = ({ title, value, icon, color, subtitle }) => (
  <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} style={{ height: '100%' }}>
    <Card className="glass-card" sx={{ height: '100%', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)', '&:hover': { transform: 'translateY(-5px)', borderColor: alpha(color, 0.3) } }}>
      <CardContent sx={{ p: 3 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <Box>
            <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.4)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.15em', fontSize: '0.65rem' }}>
              {title}
            </Typography>
            <Typography sx={{ fontWeight: 900, fontSize: '1.75rem', color: '#fff', letterSpacing: '-0.02em', mt: 0.5 }}>{value}</Typography>
            <Typography variant="caption" sx={{ color: alpha(color, 0.8), mt: 0.5, display: 'block', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              {subtitle}
            </Typography>
          </Box>
          <Box sx={{ width: 44, height: 44, borderRadius: '14px', background: alpha(color, 0.1), border: `1px solid ${alpha(color, 0.2)}`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: color }}>
            {React.cloneElement(icon, { sx: { fontSize: 22 } })}
          </Box>
        </Box>
      </CardContent>
    </Card>
  </motion.div>
);

function AuditTrail() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(25);
  const [filters, setFilters] = useState({
    entityType: '',
    action: '',
    search: '',
  });
  const [availableActions, setAvailableActions] = useState([]);
  const [sortConfig, setSortConfig] = useState({
    field: 'timestamp',
    direction: 'desc'
  });

  useEffect(() => {
    fetchLogs();
  }, [page, rowsPerPage, filters]);

  const fetchLogs = async () => {
    try {
      setLoading(true);
      const params = {
        page: page + 1,
        limit: rowsPerPage,
        ...filters,
      };
      const response = await audit.getLogs(params);
      setLogs(response.data.logs);
      setAvailableActions(response.data.filters?.actions || []);
      setError(null);
    } catch (error) {
      console.error('Error fetching audit logs:', error);
      setError('Failed to load audit logs');
    } finally {
      setLoading(false);
    }
  };

  const handleSort = (field) => {
    setSortConfig({
      field,
      direction: sortConfig.field === field && sortConfig.direction === 'asc' ? 'desc' : 'asc'
    });
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(ORANGE);
    doc.text('AUDIT COMPLIANCE REPORT', 14, 20);
    doc.setFontSize(10);
    doc.setTextColor('#6B7280');
    doc.text(`GENERATED BY MDM CORE — ${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}`, 14, 28);
    
    const tableColumn = ["TIMESTAMP", "OPERATOR", "ACTION", "ENTITY", "STATUS"];
    const tableRows = logs.map(log => [
      format(new Date(log.timestamp), 'yyyy-MM-dd HH:mm'),
      log.userName || 'SYSTEM',
      log.action,
      `${log.entityType}: ${log.entityName || log.entityId}`,
      (log.status || 'SUCCESS').toUpperCase()
    ]);

    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 35,
      theme: 'grid',
      headStyles: { fillColor: ORANGE, textColor: '#FFFFFF', fontStyle: 'bold' },
      bodyStyles: { fontSize: 9 },
      margin: { top: 35 }
    });
    
    doc.save(`audit-ledger-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  };

  const exportToCSV = () => {
    const csvData = logs.map(log => ({
      Timestamp: format(new Date(log.timestamp), 'yyyy-MM-dd HH:mm:ss'),
      Operator: log.userName || 'System',
      Action: log.action,
      EntityType: log.entityType,
      EntityId: log.entityId,
      Status: log.status || 'success',
      Metadata: JSON.stringify(log.metadata || {})
    }));
    
    const csv = Papa.unparse(csvData);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.setAttribute('download', `audit-ledger-${format(new Date(), 'yyyy-MM-dd')}.csv`);
    link.click();
  };

  const getActionIcon = (action) => {
    if (action.includes('DEVICE')) return <DeviceIcon sx={{ fontSize: 14 }} />;
    if (action.includes('UPDATE')) return <UpdateIcon sx={{ fontSize: 14 }} />;
    if (action.includes('SCHEDULE')) return <ScheduleIcon sx={{ fontSize: 14 }} />;
    if (action.includes('USER')) return <PersonIcon sx={{ fontSize: 14 }} />;
    return <HistoryIcon sx={{ fontSize: 14 }} />;
  };

  const getActionColor = (action) => {
    if (action.includes('FAILED') || action.includes('ERROR')) return '#EF4444';
    if (action.includes('CREATE') || action.includes('REGISTER')) return '#10B981';
    if (action.includes('UPDATE') || action.includes('MODIFY')) return '#3B82F6';
    if (action.includes('DELETE') || action.includes('BLOCK')) return '#F59E0B';
    return 'rgba(255,255,255,0.4)';
  };

  return (
    <PageTransition>
      <Box sx={{ maxWidth: 1600, mx: 'auto' }}>
        {/* Header Section */}
        <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: 3 }}>
          <Box>
            <Typography variant="h4" sx={{ fontWeight: 900, color: '#fff', letterSpacing: '-0.04em', mb: 1, textTransform: 'uppercase' }}>
              System <span style={{ color: ORANGE }}>Ledger</span>
            </Typography>
            <Typography sx={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.95rem', fontWeight: 600 }}>
              Complete immutable audit trail of all infrastructure operations
            </Typography>
          </Box>
          <Box sx={{ display: 'flex', gap: 2 }}>
            <Button
              variant="outlined"
              startIcon={<DownloadIcon />}
              onClick={exportToCSV}
              sx={{ borderColor: 'rgba(255,255,255,0.1)', color: 'rgba(255,255,255,0.7)', borderRadius: '12px', fontWeight: 700, px: 3, '&:hover': { borderColor: '#fff', color: '#fff', bgcolor: 'rgba(255,255,255,0.05)' } }}
            >
              Export CSV
            </Button>
            <Button
              variant="contained"
              startIcon={<DownloadIcon />}
              onClick={exportToPDF}
              sx={{ bgcolor: ORANGE, color: '#fff', borderRadius: '12px', fontWeight: 800, px: 3, boxShadow: `0 8px 25px ${alpha(ORANGE, 0.4)}`, '&:hover': { bgcolor: '#E55A2B', transform: 'translateY(-2px)' }, transition: 'all 0.2s' }}
            >
              Audit Report
            </Button>
          </Box>
        </Box>

        {error && (
          <Alert severity="error" sx={{ mb: 4, borderRadius: '12px', bgcolor: alpha('#EF4444', 0.1), color: '#EF4444', border: '1px solid rgba(239, 68, 68, 0.2)' }}>
            {error}
          </Alert>
        )}

        {/* Stats Grid */}
        <Grid container spacing={3} sx={{ mb: 4 }}>
          <Grid item xs={12} sm={6} md={3}>
            <AuditStatCard
              title="Total Events"
              value={logs.length}
              icon={<HistoryIcon />}
              color="#3B82F6"
              subtitle="System wide logs"
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <AuditStatCard
              title="Operational Success"
              value={`${logs.length ? Math.round((logs.filter(l => l.status === 'success' || !l.status).length / logs.length) * 100) : 0}%`}
              icon={<CheckCircleIcon />}
              color="#10B981"
              subtitle="Stability index"
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <AuditStatCard
              title="Security Alerts"
              value={logs.filter(l => l.status === 'failure' || l.action.includes('BLOCK')).length}
              icon={<WarningIcon />}
              color="#F59E0B"
              subtitle="Review required"
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <AuditStatCard
              title="Active Operators"
              value={new Set(logs.map(l => l.userName)).size}
              icon={<PersonIcon />}
              color={ORANGE}
              subtitle="Session count"
            />
          </Grid>
        </Grid>

        {/* Filters Section */}
        <Card className="glass-card" sx={{ mb: 4, bgcolor: 'rgba(255,255,255,0.01)' }}>
          <CardContent sx={{ p: 2.5 }}>
            <Grid container spacing={2.5} alignItems="center">
              <Grid item xs={12} md={5}>
                <TextField
                  fullWidth
                  placeholder="Query ledger by entity, operator or keyword..."
                  value={filters.search}
                  onChange={(e) => setFilters({...filters, search: e.target.value})}
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <SearchIcon sx={{ color: ORANGE, fontSize: 20 }} />
                      </InputAdornment>
                    ),
                    sx: {
                      borderRadius: '12px',
                      bgcolor: 'rgba(255,255,255,0.02)',
                      '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.05)' },
                      '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.1)' },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderColor: ORANGE },
                      color: '#fff'
                    }
                  }}
                />
              </Grid>
              <Grid item xs={12} md={3.5}>
                <FormControl fullWidth>
                  <InputLabel sx={{ color: 'rgba(255,255,255,0.4)' }}>Entity Domain</InputLabel>
                  <Select
                    value={filters.entityType}
                    label="Entity Domain"
                    onChange={(e) => setFilters({...filters, entityType: e.target.value})}
                    sx={{
                      borderRadius: '12px',
                      bgcolor: 'rgba(255,255,255,0.02)',
                      color: '#fff',
                      '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.05)' },
                      '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.1)' },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderColor: ORANGE },
                    }}
                  >
                    <MenuItem value="">All Domains</MenuItem>
                    <MenuItem value="device">Fleet Devices</MenuItem>
                    <MenuItem value="version">Build Versions</MenuItem>
                    <MenuItem value="schedule">Broadcast Schedules</MenuItem>
                    <MenuItem value="user">Operator Accounts</MenuItem>
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} md={3.5}>
                <FormControl fullWidth>
                  <InputLabel sx={{ color: 'rgba(255,255,255,0.4)' }}>Operation Type</InputLabel>
                  <Select
                    value={filters.action}
                    label="Operation Type"
                    onChange={(e) => setFilters({...filters, action: e.target.value})}
                    sx={{
                      borderRadius: '12px',
                      bgcolor: 'rgba(255,255,255,0.02)',
                      color: '#fff',
                      '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.05)' },
                      '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.1)' },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderColor: ORANGE },
                    }}
                  >
                    <MenuItem value="">All Operations</MenuItem>
                    {availableActions.map(action => (
                      <MenuItem key={action} value={action}>{action.replace(/_/g, ' ')}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
            </Grid>
          </CardContent>
        </Card>

        {/* Ledger Table */}
        <Card className="glass-card" sx={{ overflow: 'hidden' }}>
          <TableContainer sx={{ maxHeight: 'calc(100vh - 480px)' }}>
            <Table stickyHeader>
              <TableHead>
                <TableRow>
                  <TableCell onClick={() => handleSort('timestamp')} sx={{ bgcolor: 'rgba(20, 20, 35, 0.9) !important', color: 'rgba(255,255,255,0.4) !important', fontWeight: 800, fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.1em', cursor: 'pointer', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                    Timestamp {sortConfig.field === 'timestamp' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                  </TableCell>
                  <TableCell onClick={() => handleSort('action')} sx={{ bgcolor: 'rgba(20, 20, 35, 0.9) !important', color: 'rgba(255,255,255,0.4) !important', fontWeight: 800, fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.1em', cursor: 'pointer', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                    Operation {sortConfig.field === 'action' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                  </TableCell>
                  <TableCell onClick={() => handleSort('entityType')} sx={{ bgcolor: 'rgba(20, 20, 35, 0.9) !important', color: 'rgba(255,255,255,0.4) !important', fontWeight: 800, fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.1em', cursor: 'pointer', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                    Target Entity {sortConfig.field === 'entityType' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                  </TableCell>
                  <TableCell onClick={() => handleSort('userName')} sx={{ bgcolor: 'rgba(20, 20, 35, 0.9) !important', color: 'rgba(255,255,255,0.4) !important', fontWeight: 800, fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.1em', cursor: 'pointer', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                    Operator {sortConfig.field === 'userName' && (sortConfig.direction === 'asc' ? '↑' : '↓')}
                  </TableCell>
                  <TableCell sx={{ bgcolor: 'rgba(20, 20, 35, 0.9) !important', color: 'rgba(255,255,255,0.4) !important', fontWeight: 800, fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.1em', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                    Status
                  </TableCell>
                  <TableCell sx={{ bgcolor: 'rgba(20, 20, 35, 0.9) !important', borderBottom: '1px solid rgba(255,255,255,0.05)' }}></TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={6} sx={{ py: 10, textAlign: 'center', borderBottom: 'none' }}>
                      <LinearProgress sx={{ maxWidth: 200, mx: 'auto', borderRadius: 2, bgcolor: 'rgba(255,255,255,0.05)', '& .MuiLinearProgress-bar': { bgcolor: ORANGE } }} />
                      <Typography sx={{ color: 'rgba(255,255,255,0.4)', mt: 2, fontWeight: 700, fontSize: '0.85rem' }}>SYNCING LEDGER DATA...</Typography>
                    </TableCell>
                  </TableRow>
                ) : logs.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} sx={{ py: 12, textAlign: 'center', borderBottom: 'none' }}>
                      <HistoryIcon sx={{ fontSize: 48, color: 'rgba(255,255,255,0.05)', mb: 2 }} />
                      <Typography sx={{ color: 'rgba(255,255,255,0.3)', fontWeight: 800, fontSize: '1rem' }}>NO RECORDS FOUND IN CURRENT DOMAIN</Typography>
                    </TableCell>
                  </TableRow>
                ) : (
                  logs.map((log) => (
                    <TableRow key={log._id} hover sx={{ '&:hover': { bgcolor: 'rgba(255,255,255,0.02)' } }}>
                      <TableCell sx={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                        <Tooltip title={format(new Date(log.timestamp), 'PPpp')}>
                          <Typography sx={{ color: '#fff', fontSize: '0.85rem', fontWeight: 600 }}>
                            {formatDistance(new Date(log.timestamp), new Date(), { addSuffix: true })}
                          </Typography>
                        </Tooltip>
                        <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.3)', fontWeight: 700 }}>
                          {format(new Date(log.timestamp), 'HH:mm:ss.SSS')}
                        </Typography>
                      </TableCell>
                      <TableCell sx={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                          <Box sx={{ width: 28, height: 28, borderRadius: '8px', bgcolor: alpha(getActionColor(log.action), 0.1), border: `1px solid ${alpha(getActionColor(log.action), 0.2)}`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: getActionColor(log.action) }}>
                            {getActionIcon(log.action)}
                          </Box>
                          <Typography sx={{ color: '#fff', fontWeight: 700, fontSize: '0.85rem', letterSpacing: '0.01em' }}>
                            {log.action.replace(/_/g, ' ')}
                          </Typography>
                        </Box>
                      </TableCell>
                      <TableCell sx={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                        <Typography sx={{ color: 'rgba(255,255,255,0.8)', fontSize: '0.85rem', fontWeight: 700 }}>
                          {log.entityName || log.entityId.substring(0, 12) + '...'}
                        </Typography>
                        <Typography variant="caption" sx={{ color: ORANGE, fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                          {log.entityType}
                        </Typography>
                      </TableCell>
                      <TableCell sx={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                          <PersonIcon sx={{ color: 'rgba(255,255,255,0.2)', fontSize: 18 }} />
                          <Box>
                            <Typography sx={{ color: '#fff', fontSize: '0.85rem', fontWeight: 700 }}>
                              {log.userName || 'SYSTEM'}
                            </Typography>
                            <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.3)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                              {log.userRole || 'SERVICE'}
                            </Typography>
                          </Box>
                        </Box>
                      </TableCell>
                      <TableCell sx={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                        <Chip
                          label={log.status || 'SUCCESS'}
                          size="small"
                          sx={{
                            fontWeight: 900,
                            fontSize: '0.65rem',
                            height: 20,
                            bgcolor: log.status === 'failure' ? alpha('#EF4444', 0.1) : alpha('#10B981', 0.1),
                            color: log.status === 'failure' ? '#EF4444' : '#10B981',
                            border: `1px solid ${log.status === 'failure' ? alpha('#EF4444', 0.2) : alpha('#10B981', 0.2)}`,
                            textTransform: 'uppercase',
                            letterSpacing: '0.05em'
                          }}
                        />
                      </TableCell>
                      <TableCell sx={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }} align="right">
                        <IconButton size="small" sx={{ color: 'rgba(255,255,255,0.2)', '&:hover': { color: ORANGE, bgcolor: 'rgba(255,255,255,0.05)' } }}>
                          <MoreIcon fontSize="small" />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>

          <TablePagination
            rowsPerPageOptions={[25, 50, 100]}
            component="div"
            count={logs.length}
            rowsPerPage={rowsPerPage}
            page={page}
            onPageChange={(e, newPage) => setPage(newPage)}
            onRowsPerPageChange={(e) => {
              setRowsPerPage(parseInt(e.target.value, 10));
              setPage(0);
            }}
            sx={{
              color: 'rgba(255,255,255,0.5)',
              borderTop: '1px solid rgba(255,255,255,0.05)',
              '.MuiTablePagination-selectIcon': { color: 'rgba(255,255,255,0.4)' },
              '.MuiTablePagination-actions': { color: 'rgba(255,255,255,0.4)' }
            }}
          />
        </Card>
      </Box>
    </PageTransition>
  );
}

export default AuditTrail;